[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.3"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["homebrew"]
# Homebrew tap to publish to
tap = "brianm/homebrew-tools"
# Publish jobs to run
publish-jobs = ["homebrew"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]

# Include man page in releases
include = ["doc/bdsh.1"]

# Runtime dependencies
[dist.dependencies.homebrew]
tmux = { stage = ["run"] }
